<?php

/**
 * BaseBank
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $branch_id
 * @property integer $sectional_id
 * @property Branch $Branch
 * @property Doctrine_Collection $Profiles
 * @property Doctrine_Collection $Bills
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getBranchId()     Returns the current record's "branch_id" value
 * @method integer             getSectionalId()  Returns the current record's "sectional_id" value
 * @method Branch              getBranch()       Returns the current record's "Branch" value
 * @method Doctrine_Collection getProfiles()     Returns the current record's "Profiles" collection
 * @method Doctrine_Collection getBills()        Returns the current record's "Bills" collection
 * @method Bank                setId()           Sets the current record's "id" value
 * @method Bank                setName()         Sets the current record's "name" value
 * @method Bank                setBranchId()     Sets the current record's "branch_id" value
 * @method Bank                setSectionalId()  Sets the current record's "sectional_id" value
 * @method Bank                setBranch()       Sets the current record's "Branch" value
 * @method Bank                setProfiles()     Sets the current record's "Profiles" collection
 * @method Bank                setBills()        Sets the current record's "Bills" collection
 * 
 * @package    limbo
 * @subpackage model
 * @author     Damian Suarez / Laura Melo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBank extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bank');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('branch_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sectional_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, Doctrine_Core::EXPORT_ALL);

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Branch', array(
             'local' => 'branch_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Profile as Profiles', array(
             'local' => 'id',
             'foreign' => 'bank_id'));

        $this->hasMany('Bill as Bills', array(
             'local' => 'id',
             'foreign' => 'bank_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}