<?php

/**
 * BaseBranch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $number
 * @property string $description
 * @property integer $sectional_id
 * @property integer $locality_id
 * @property integer $state_id
 * @property Sectional $Sectional
 * @property Doctrine_Collection $Banks
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getNumber()       Returns the current record's "number" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method integer             getSectionalId()  Returns the current record's "sectional_id" value
 * @method integer             getLocalityId()   Returns the current record's "locality_id" value
 * @method integer             getStateId()      Returns the current record's "state_id" value
 * @method Sectional           getSectional()    Returns the current record's "Sectional" value
 * @method Doctrine_Collection getBanks()        Returns the current record's "Banks" collection
 * @method Branch              setId()           Sets the current record's "id" value
 * @method Branch              setNumber()       Sets the current record's "number" value
 * @method Branch              setDescription()  Sets the current record's "description" value
 * @method Branch              setSectionalId()  Sets the current record's "sectional_id" value
 * @method Branch              setLocalityId()   Sets the current record's "locality_id" value
 * @method Branch              setStateId()      Sets the current record's "state_id" value
 * @method Branch              setSectional()    Sets the current record's "Sectional" value
 * @method Branch              setBanks()        Sets the current record's "Banks" collection
 * 
 * @package    limbo
 * @subpackage model
 * @author     Damian Suarez / Laura Melo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBranch extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('branch');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('number', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sectional_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('locality_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('state_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, Doctrine_Core::EXPORT_ALL);

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Sectional', array(
             'local' => 'sectional_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Bank as Banks', array(
             'local' => 'id',
             'foreign' => 'branch_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}