<?php

/**
 * BaseMGGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $author_id
 * @property string $title
 * @property clob $description
 * @property Doctrine_Collection $Albums
 * @property Doctrine_Collection $Photos
 * @property sfGuardUser $Author
 * @property Doctrine_Collection $MGAlbumGallery
 * @property Doctrine_Collection $MGGalleryPhoto
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getAuthorId()       Returns the current record's "author_id" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method clob                getDescription()    Returns the current record's "description" value
 * @method Doctrine_Collection getAlbums()         Returns the current record's "Albums" collection
 * @method Doctrine_Collection getPhotos()         Returns the current record's "Photos" collection
 * @method sfGuardUser         getAuthor()         Returns the current record's "Author" value
 * @method Doctrine_Collection getMGAlbumGallery() Returns the current record's "MGAlbumGallery" collection
 * @method Doctrine_Collection getMGGalleryPhoto() Returns the current record's "MGGalleryPhoto" collection
 * @method MGGallery           setId()             Sets the current record's "id" value
 * @method MGGallery           setAuthorId()       Sets the current record's "author_id" value
 * @method MGGallery           setTitle()          Sets the current record's "title" value
 * @method MGGallery           setDescription()    Sets the current record's "description" value
 * @method MGGallery           setAlbums()         Sets the current record's "Albums" collection
 * @method MGGallery           setPhotos()         Sets the current record's "Photos" collection
 * @method MGGallery           setAuthor()         Sets the current record's "Author" value
 * @method MGGallery           setMGAlbumGallery() Sets the current record's "MGAlbumGallery" collection
 * @method MGGallery           setMGGalleryPhoto() Sets the current record's "MGGalleryPhoto" collection
 * 
 * @package    limbo
 * @subpackage model
 * @author     Damian Suarez / Laura Melo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMGGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mdgalledy_gallery');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('author_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MGAlbum as Albums', array(
             'refClass' => 'MGAlbumGallery',
             'local' => 'gallery_id',
             'foreign' => 'album_id'));

        $this->hasMany('MGPhoto as Photos', array(
             'refClass' => 'MGGalleryPhoto',
             'local' => 'gallery_id',
             'foreign' => 'photo_id'));

        $this->hasOne('sfGuardUser as Author', array(
             'local' => 'author_id',
             'foreign' => 'id'));

        $this->hasMany('MGAlbumGallery', array(
             'local' => 'id',
             'foreign' => 'gallery_id'));

        $this->hasMany('MGGalleryPhoto', array(
             'local' => 'id',
             'foreign' => 'gallery_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}