<?php

/**
 * MGAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    limbo
 * @subpackage model
 * @author     Damian Suarez / Laura Melo
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MGAlbum extends PluginMGAlbum
{
}
