options:
  collate: utf8_unicode_ci
  charset: utf8
attributes:
  export: all

Profile:
  actAs:
    - Timestampable
  tableName:                    profile
  columns:
    id:                         {type: integer, primary: true, autoincrement: true}
    sf_guard_user_id:           integer(4)
    membership_number:          {type: integer}
    first_name:                 {type: string(100), notnull: true}
    last_name:                  {type: string(100), notnull: true}
    birth_date:                 {type: date}
    documment_type:             {type: enum, values: [ dni, le ], default: dni}
    documment_number:           {type: string(15) }
    phone:                      {type: string(40)}
    movil:                      {type: string(40)}
    email:                      {type: string(60)}
    addres:                     {type: string(100)}
    addres_2:                   {type: string(100)}
    locality_id:                {type: integer}
  relations:
    sfGuardUser:                {local: sf_guard_user_id, foreign: id, foreignType: one, onDelete: CASCADE}